"""empty message

Revision ID: 49d7e206a1a0
Revises: 
Create Date: 2021-08-02 21:22:55.462880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49d7e206a1a0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('fridge',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customer',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_name', sa.String(length=30), nullable=True),
    sa.Column('fridge_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fridge_id'], ['fridge.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_name')
    )
    op.drop_table('user')
    op.add_column('item', sa.Column('category_id', sa.Integer(), nullable=True))
    op.add_column('item', sa.Column('fridge_id', sa.Integer(), nullable=True))
    op.add_column('item', sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
    op.add_column('item', sa.Column('item_inventory', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'item', ['id'])
    op.create_unique_constraint(None, 'item', ['category_id'])
    op.create_unique_constraint(None, 'item', ['fridge_id'])
    op.create_foreign_key(None, 'item', 'category', ['category_id'], ['id'])
    op.create_foreign_key(None, 'item', 'fridge', ['fridge_id'], ['id'])
    op.drop_column('item', 'tag')
    op.drop_column('item', 'item_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('item_id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.add_column('item', sa.Column('tag', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'item', type_='foreignkey')
    op.drop_constraint(None, 'item', type_='foreignkey')
    op.drop_constraint(None, 'item', type_='unique')
    op.drop_constraint(None, 'item', type_='unique')
    op.drop_constraint(None, 'item', type_='unique')
    op.drop_column('item', 'item_inventory')
    op.drop_column('item', 'id')
    op.drop_column('item', 'fridge_id')
    op.drop_column('item', 'category_id')
    op.create_table('user',
    sa.Column('user_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('user_id', name='user_pkey'),
    sa.UniqueConstraint('username', name='user_username_key')
    )
    op.drop_table('customer')
    op.drop_table('fridge')
    op.drop_table('category')
    # ### end Alembic commands ###
